# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "JvYRBuVQaSWLEIx4XfdkbkwOGUOzEyPwv3hfQ14jvqC/YEUeCMb7wP3cJHlkNoFeC0zEDcSAK0T46eT/GCV77Dmbb5ykA9rHELLSjfRAR/mrvk15ClzSlDQ7Nz0URcpeK51DxWobA0jaKbYWglKxrpgbEnYalAuXuy16TaCyMu/xDz6zD56Yk8LyhK5D2Oz5P3qrvApx28Q3YHprM2phr+sbGrYUeD6Kxakw+1YUmWmmWXNZkxAhe0bmcSiC+JoEMef1kvJ5YA/IhPel6N1HWIAzMylEmgPF6uu3bDsorYzrca6vsYIFXc2JIO/M2NNWFoJQVLaiMwa+Mj5/6Ii/h9NJt5we2oqyaiUVcJvS9x3WexEjrh33juf9iMQLPJIBKfZuiBz7/YHR9mPMOMVZEwqdFNKlGTx/9dord9lkCGV3zo1HYLRL6SGlxr/4TqpAHYZ1k8nrQm38Vh3u11+G0qIsVX5DsV64NaVL9MnewyXycJw1UM42yDTYhpKCk63AtyEwyLBQiC+e/w2iXckRp0inuBwtgq1GcNsP+8jfQ9zQjZQAdmeCn+WP2khslu2J0kStqnW0RkLQs0E5/5uduOXfqU7c+8+IY80FHyjUmAXxq2zpVzDPtdGeA/ADndrNcYo+eK43vMrha6ikaOBN4pc1sAjvzOp6yRG8w10XV94="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
