# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1
    - CONFIG=osx_r_base3.5.1

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "lcK9PSeojW64G+37bqO6AVEyveMtkhaNrS3zeysvQ0byqjduRg2ycWTv3hFqVgRiYAi117pSWqONuRmA1DIKCJdTYvyLjJF/YVo04mrjzAT6DE4UChGM/YsWVT8yEEc9iwxL4XFBQJqGhiEHBs5jHmAn3bvrQsgqkRnqvKetV/84cf4aUuhMMmcDoPT845qmXv7beE3oK1ceFTDifZfHd8qLRDjPQ3NXr/glQ3YfvgX6B9drAlOvq6RVciA1Xn8OIu8YCm2CrXHhMJIjSItxL4ox09+L8odS2HDIZ8epkI+VBPTw83d5FfmLWddfgEG6frptELF9dMkZG8DcALvd4V8dp9QMPselrEg/mpNHRZ3qv3/PdPEHrJ4WpHEJAKL9v5e+ro4cNTe7BPA1PaisjVBuV7JYDOpPTqRv5C/pNq6sT6mKJL+EBHX9RgrOXX4I5bFa5EPhhKSZXvX7g33tB/3wGMFIMaro2unwSx4Zk9EhhG9Q6rNPwvaC9TC2vOpl0d9JbcAkGKH1EkoCDZY7ZenAIK0aO4xBLTsO1NDzpVFbVcuH5xDz060KNvHGCN0RfBNoF1pw+e82y0QgJ75u/pOIrJts1Zat2ISp0s4dhq/gtQ/PCj34Ymrznsj8LTAE3NUsrGT2OTPq0fwA47jxY++njW+pcUUfJqJ7ugOawY8="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
