travis:
  secure:
    BINSTAR_TOKEN: JvYRBuVQaSWLEIx4XfdkbkwOGUOzEyPwv3hfQ14jvqC/YEUeCMb7wP3cJHlkNoFeC0zEDcSAK0T46eT/GCV77Dmbb5ykA9rHELLSjfRAR/mrvk15ClzSlDQ7Nz0URcpeK51DxWobA0jaKbYWglKxrpgbEnYalAuXuy16TaCyMu/xDz6zD56Yk8LyhK5D2Oz5P3qrvApx28Q3YHprM2phr+sbGrYUeD6Kxakw+1YUmWmmWXNZkxAhe0bmcSiC+JoEMef1kvJ5YA/IhPel6N1HWIAzMylEmgPF6uu3bDsorYzrca6vsYIFXc2JIO/M2NNWFoJQVLaiMwa+Mj5/6Ii/h9NJt5we2oqyaiUVcJvS9x3WexEjrh33juf9iMQLPJIBKfZuiBz7/YHR9mPMOMVZEwqdFNKlGTx/9dord9lkCGV3zo1HYLRL6SGlxr/4TqpAHYZ1k8nrQm38Vh3u11+G0qIsVX5DsV64NaVL9MnewyXycJw1UM42yDTYhpKCk63AtyEwyLBQiC+e/w2iXckRp0inuBwtgq1GcNsP+8jfQ9zQjZQAdmeCn+WP2khslu2J0kStqnW0RkLQs0E5/5uduOXfqU7c+8+IY80FHyjUmAXxq2zpVzDPtdGeA/ADndrNcYo+eK43vMrha6ikaOBN4pc1sAjvzOp6yRG8w10XV94=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
