travis:
  secure:
    BINSTAR_TOKEN: cVxoPnClKqGd/CIXKSgBrz5j6S5QAJp3NYJi5aVGRKUrtGsUL+i6VvFjaLI0IILfWQIE2JxVcqc/0w5OOdrRUoUXkCwjcRTkImQQJX0sGqmFJvr1j2UwjXJ+ts2p1uHGHKDzMTZ26hOKDoRCPXeyPjXkNtDvStRMAO0LKt7GOhZJnob28bE3m2zFNYyBbw2NlnwG+OSFD2cqpwW2BxUxlMNe2HM2njuiHKTM9Yx1SGioJzuIWbsqsI3vmfQTl2lX9UauACzHcvvvtxLnxRQ+opvAHIkzyC9xnoxWWTu8czHUugtCOAdJC9KPXzJZbTf1uQ/YGZbWTNT2x/br3ZwRAnn88Yisp0pEBjAxAhxN5OqWA9kRvA8I8WS2G+hpyakp5FBhZbkxjMUZxDMSIFa2eSZl2IerYOW8uRQlFEbxHgW01bVbJtV3BVFeVu0VLL2L+IoZ+zFUqtGzzJUoO78cX/eFvl0i3NZ8Q6oVwEUkJdouIEiEm5v1TEswaWRM0C2kvO4gsbWcniMkVlcXL08mUY+o1ilVBmwSd3dtRpkCpqKyNUAmKhzO8GTU7cDmHZ/HY3RUEX35cYWXn8QiT2WJk1JWmQybiqqL2fQBke6ErOPUJpmcHq5E5dJyNpQR/4oBwdbxhyKXf1xNE7oQv5a1AYCKLhwp1YmyDEqeOOiSmmc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
