travis:
  secure:
    BINSTAR_TOKEN: JTfpBHCa/sSZX1w7YAwtKKgoOxs1bjCBQRV2R1Sts8nY44X2CZI++fzR/o7el+8sRWwyD55Ud3MPyWR8ZmhGfHMdkblV9TaqAaAd3dGPbKolvIEvTKwakaGBGgIKlCT7cVvoBD9m9XJ4Jbf8bfw8IcdHynZLN+nN559rBk4FguPhAig9MkopovGTda+6Z8TPGOy5NvNTIS/CHPdeFi+gqOOApswHBEjITMozaO8sqCwbKZZ50g8Nw5omxmUtHGGRqQ9G95rD4Z72DPy5FMlI1C92SvKnNUjOlvwAVjTNynK5oXDuM6vtOI7almROkBbcOtMqbiM1gVAxOJ3vNbM+5kBLGTMCrDI0pF3rrxF/ayR7h489ZuEz/PUwHB8TJk4HqRrHAeM6+qhwDDokgL1Ar6gQyg+C97CMIaXM7hwqr8Y4JWPbwJyTFZIDd61jTSdIzqgN3Lr9PbXQODpdy8/Dn0junD2zDAVOaaRd/Ra0vFgu1KwXEwFb4Yk6CGK/xaqFPsH/g8EXFRB6vrNGHOsCywHRKxLEAifhIHGkCAPUvq0GTpe0XeDuO7p7YSgjF4L+3WxmbwEiBZ5Gev6arTBKMw9NAp57RFNy++dGFZcSN17AB1bzU9ShBsxdFJIaUma40kqLuXm9O2RDeDOgvpaLU2gNgYzMmN96sfDmGfXEROI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
