appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: lcK9PSeojW64G+37bqO6AVEyveMtkhaNrS3zeysvQ0byqjduRg2ycWTv3hFqVgRiYAi117pSWqONuRmA1DIKCJdTYvyLjJF/YVo04mrjzAT6DE4UChGM/YsWVT8yEEc9iwxL4XFBQJqGhiEHBs5jHmAn3bvrQsgqkRnqvKetV/84cf4aUuhMMmcDoPT845qmXv7beE3oK1ceFTDifZfHd8qLRDjPQ3NXr/glQ3YfvgX6B9drAlOvq6RVciA1Xn8OIu8YCm2CrXHhMJIjSItxL4ox09+L8odS2HDIZ8epkI+VBPTw83d5FfmLWddfgEG6frptELF9dMkZG8DcALvd4V8dp9QMPselrEg/mpNHRZ3qv3/PdPEHrJ4WpHEJAKL9v5e+ro4cNTe7BPA1PaisjVBuV7JYDOpPTqRv5C/pNq6sT6mKJL+EBHX9RgrOXX4I5bFa5EPhhKSZXvX7g33tB/3wGMFIMaro2unwSx4Zk9EhhG9Q6rNPwvaC9TC2vOpl0d9JbcAkGKH1EkoCDZY7ZenAIK0aO4xBLTsO1NDzpVFbVcuH5xDz060KNvHGCN0RfBNoF1pw+e82y0QgJ75u/pOIrJts1Zat2ISp0s4dhq/gtQ/PCj34Ymrznsj8LTAE3NUsrGT2OTPq0fwA47jxY++njW+pcUUfJqJ7ugOawY8=}
bot:
  automerge: true
